quejas/__init__.py
from flask import Blueprint

queja = Blueprint('queja', __name__, template_folder='templates')

from . import routes 

quejas/routes.py
from . import queja
from flask import Flask, request, render_template
from conexionBD import *  #Importando conexion BD
from funciones import *  #Importando mis Funciones

from babel import numbers, dates
from datetime import date, datetime, time
from flask_babel import Babel, gettext, refresh; refresh()

app = Flask(__name__)

app.config ['BABEL_DEFAULT_LOCALE'] = 'en'
babel = Babel(app)

def get_locale():
    return request.accept_languages.best_match('en', 'es', 'fr ')
babel = Babel(app, locale_selector=get_locale)

ENVIANOS_SOLICITUD = gettext('ENVIANOS TU SOLICITUD')
Nombre = gettext('Nombre')
Apellido = gettext('Apellido')
Correo = gettext('Correo')
Sexo = gettext('Sexo')
Te_gusta_cuadros = gettext(' ¿Te gusta la paginade C&C "cuadros y mas cuadros"?')
Si = gettext('Si')
No = gettext('No')
Describe_peticion = gettext('Describe tu peticion:')


@queja.route('/quejas') 
def quejas(): 
    return render_template('quejas.html', dataLogin = dataLoginSesion())


@queja.route('/form', methods=['GET', 'POST'])
def registrarForm():
    msg =''
    if request.method == 'POST':
        nombre              = request.form['nombre']
        apellido            = request.form['apellido']
        correo              = request.form['correo']
        sexo                = request.form['sexo']
        likes               = request.form['likes']
        descripcion         = request.form['descripcion']
        
        conexion_MySQLdb = connectionBD()
        cursor           = conexion_MySQLdb.cursor(dictionary=True)
        
        '''
        cursor.execute('INSERT INTO pqrs (nombre, apellido, correo, sexo, likes, descripcion) VALUES (%s, %s, %s, %s, %s, %s)', (nombre, apellido, correo, sexo, likes, descripcion))
        ResultInsert = conexion_MySQLdb.commit()
        '''
            
        sql         = ("INSERT INTO pqrs(nombre, apellido, correo, sexo, likes, descripcion) VALUES (%s, %s, %s, %s, %s, %s)")
        valores     = (nombre, apellido, correo, sexo, likes, descripcion)
        cursor.execute(sql, valores)
        conexion_MySQLdb.commit()
        
        cursor.close() #Cerrando conexion SQL
        conexion_MySQLdb.close() #cerrando conexion de la BD
        msg = 'Registro con exito'
        
        print(cursor.rowcount, "registro insertado")
        print("1 registro insertado, id", cursor.lastrowid)
  
        return render_template('quejas.html', msg='Formulario enviado')
    else:
        return render_template('quejas.html', msg = 'Metodo HTTP incorrecto')

quejas/templates/quejas.html
{% extends 'layout.html' %}


{% block contenido2 %} 
    <style>
        .msg{
            text-align: center;
            font-size: 4rem;
            line-height: 1em;
            font-weight: 800;
            color: orange;
            background: #f2f4f8;
            display: flex;
            justify-content: center;
            margin: 0 auto;
        }
    </style>


    <div class="content-wrapper" style="background-image: url('../static/img/fondo4.png');">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    
                    <div id="contenedor" class="col-12" align="center">
                        <div id="contenedor2" class="col-9" align="left">
                            <div class="card border-info">
                                <div class="card-body">
                                    <ul class="list-group list-group-light">
                                        <li class="list-group-item">
                                            <div class="container">
                                                <div class="row">
                                                    <div class="col-12">
                                                        <section class="content">
                                                            <div class="row">
                                                                <div class="col-md-12">
                                                                   
                                                                        <div class="card2 card-primary">
                                                                            <div class="card-header">
                                                                                <h3 class="card-title">P.Q.R.S.</h3>
                                                                            </div>
                                                                            <div class="container " style="background-color: #BFC4C4;">
<!--.......................................................................................-->
                                                                                <div class="container">
                                                                                    <div class="row">
                                                                                        <div class="Column" style="margin-top: 5%">
                                                                                            <h3>
                                                                                                <strong>
                                                                                                    <b>ENVIANOS TU SOLICITUD</b>
                                                                                                </strong>
                                                                                                <hr>
                                                                                            </h3>

                                                                                            <form action="{{ url_for('queja.registrarForm') }}" method="POST" autocomplete="off">
                                                                                                <div class="row">
                                                                                                    <div class="six columns">
                                                                                                        <label for="nombre">Nombre</label>
                                                                                                        <input type="text" name="nombre" class="u-full-width">
                                                                                                        <br>
                                                                                                    </div>

                                                                                                    <div class="six columns">
                                                                                                        <br>
                                                                                                        <label for="apellido">Apellido</label>
                                                                                                        <input type="text" name="apellido" class="u-full-width">
                                                                                                        <br>
                                                                                                    </div>

                                                                                                    <div class="six columns">
                                                                                                        <br>
                                                                                                        <label for="correo">Correo</label>
                                                                                                        <input type="email" placeholder="correo@ejemplo.com" required aria-required="true" pattern="^.+@.+\.[a-zA-Z]{2,63}$" maxlength="700" aria-label="correo@ejemplo.com"
                                                                                                        value aria-invalid="false" name="correo" class="u-full-width">
                                                                                                    </div>

                                                                                                    <div class="six columns">
                                                                                                        <br>
                                                                                                        <label for="sexo">Sexo</label>
                                                                                                        <select class="u-full-width" name="sexo">
                                                                                                            <option value="Masculino">Masculino</option>
                                                                                                            <option value="Femenino">Femenino</option>
                                                                                                        </select>
                                                                                                    </div>
                                                                                                </div>
                                                                                                <br>
                                                                                                <div class="row">
                                                                                                    <div class="six columns">
                                                                                                        <label class="example-send-yourself-copy">
                                                                                                            ¿Te gusta la paginade C&C "cuadros y mas cuadros"? <br>
                                                                                                            <input type="radio" name="likes" value="1" checked>
                                                                                                            <span class="label-body">Si</span>
                                                                                                        </label>
                                                                                                        <br>
                                                                                                        <label class="example-send-yourself-copy">
                                                                                                            <input type="radio" name="likes" value="0">
                                                                                                            <span class="label-body">No</span>
                                                                                                        </label>
                                                                                                        <br>
                                                                                                    </div>
                                                                                                    
                                                                                                    <div class="six columns">
                                                                                                        <br>
                                                                                                        <label for="perfil">Describe tu peticion:</label><br>
                                                                                                        <textarea name="descripcion" class="u-full w-50 "></textarea>
                                                                                                    </div>
                                                                                                </div>
                                                                                                <br>
                                                                                                <div class="row centered">
                                                                                                    <div class="seven columns">
                                                                                                        <input class="btn btn-alert" type="submit" value="Enviar mi formulario">
                                                                                                        
                                                                                                    </div>
                                                                                                </div>
                                                                                            </form>
                                                                                            <br>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                                <script>
                                                                                setTimeout(function(){
                                                                                    elementoP = document.querySelector('.msg');
                                                                                    elementoP.style.display = 'none';
                                                                                }, 2000);
                                                                                </script>
<!--.......................................................................................-->
                                                                            </div>
                                                                        </div>
                                                                  
                                                                </div>
                                                            </div>
                                                        </section>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endblock %}