contactos/__init__.py
from flask import Blueprint

contacto = Blueprint('contacto', __name__, template_folder='templates')

from . import routes

contactos/routes.py
from . import contacto
from flask import render_template
from flask import Flask, session, render_template, request, redirect, url_for
from conexionBD import *  #Importando conexion BD
from funciones import *  #Importando mis Funciones

from babel import numbers, dates
from datetime import date, datetime, time
from flask_babel import Babel, gettext, refresh; refresh()

app = Flask(__name__)

@contacto.route('/contactos')
def contactos():
     return render_template('contactos.html',dataLogin = dataLoginSesion())

app.config ['BABEL_DEFAULT_LOCALE'] = 'en'
babel = Babel(app)

def get_locale():
    return request.accept_languages.best_match('en', 'es', 'fr ')
babel = Babel(app, locale_selector=get_locale)


SUSCRIBETE = gettext('SUSCRIBETE')
Se_primero_recibir_información_nuestras_promociones = gettext('Sé el primero en recibir información de nuestras promociones')
Enviar = gettext('Enviar')
Siguenos_nuestras_redes_sociales = gettext('Siguenos en nuestras redes sociales')

quejas/__init__.py
from flask import Blueprint

queja = Blueprint('queja', __name__, template_folder='templates')

from . import routes 

quejas/routes.py
from . import queja
from flask import Flask, request, render_template
from conexionBD import *  #Importando conexion BD
from funciones import *  #Importando mis Funciones

from babel import numbers, dates
from datetime import date, datetime, time
from flask_babel import Babel, gettext, refresh; refresh()

app = Flask(__name__)

app.config ['BABEL_DEFAULT_LOCALE'] = 'en'
babel = Babel(app)

def get_locale():
    return request.accept_languages.best_match('en', 'es', 'fr ')
babel = Babel(app, locale_selector=get_locale)

ENVIANOS_SOLICITUD = gettext('ENVIANOS TU SOLICITUD')
Nombre = gettext('Nombre')
Apellido = gettext('Apellido')
Correo = gettext('Correo')
Sexo = gettext('Sexo')
Te_gusta_cuadros = gettext(' ¿Te gusta la paginade C&C "cuadros y mas cuadros"?')
Si = gettext('Si')
No = gettext('No')
Describe_peticion = gettext('Describe tu peticion:')


@queja.route('/quejas') 
def quejas(): 
    return render_template('quejas.html', dataLogin = dataLoginSesion())


@queja.route('/form', methods=['GET', 'POST'])
def registrarForm():
    msg =''
    if request.method == 'POST':
        nombre              = request.form['nombre']
        apellido            = request.form['apellido']
        correo              = request.form['correo']
        sexo                = request.form['sexo']
        likes               = request.form['likes']
        descripcion         = request.form['descripcion']
        
        conexion_MySQLdb = connectionBD()
        cursor           = conexion_MySQLdb.cursor(dictionary=True)
        
        '''
        cursor.execute('INSERT INTO pqrs (nombre, apellido, correo, sexo, likes, descripcion) VALUES (%s, %s, %s, %s, %s, %s)', (nombre, apellido, correo, sexo, likes, descripcion))
        ResultInsert = conexion_MySQLdb.commit()
        '''
            
        sql         = ("INSERT INTO pqrs(nombre, apellido, correo, sexo, likes, descripcion) VALUES (%s, %s, %s, %s, %s, %s)")
        valores     = (nombre, apellido, correo, sexo, likes, descripcion)
        cursor.execute(sql, valores)
        conexion_MySQLdb.commit()
        
        cursor.close() #Cerrando conexion SQL
        conexion_MySQLdb.close() #cerrando conexion de la BD
        msg = 'Registro con exito'
        
        print(cursor.rowcount, "registro insertado")
        print("1 registro insertado, id", cursor.lastrowid)
  
        return render_template('quejas.html', msg='Formulario enviado')
    else:
        return render_template('quejas.html', msg = 'Metodo HTTP incorrecto')

templates/contactos.html
{% extends './layout.html' %}


{% block contenido2 %} 


    <div class="content-wrapper" style="background-image: url('../static/img/fondo4.png');">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">


                    <div id="contenedor" class="col-12" align="center">
                        <br>
                        <p id="txt2">SUSCRIBETE</p>

                        <img src="../static/img/logoCuadros.png" alt="C&C" height="200" width="200">
                        <br><br><br>
                        <h3 id="txt8">Sé el primero en recibir información de nuestras promociones</h3>
                        <br><br>

                        <div class="12">
                            <br>
                            <input id="emailconta" type="email" placeholder="correo@ejemplo.com" required aria-required="true" pattern="^.+@.+\.[a-zA-Z]{2,63}$" maxlength="700" aria-label="correo@ejemplo.com"
                            value aria-invalid="false">
                            <button type="button" class="btn btn-success ">Enviar</button>
                        </div>
                        <br>
                    </div>
                </div>

            </div>
        </div>
        <div id="contenedor4" align="center">
            <br>
            <h5 class="textos" id="txt4">Siguenos en nuestras redes sociales</h5>
            <br>
            <a class="botonContacto" href="https://www.facebook.com/Cuadrosymascuadros999"  target="_blank">
                <img src="../static/img/iconof.png" alt="Facebook">
                &nbsp &nbsp&nbsp &nbsp
            </a>

            <a  class="botonContacto" href="https://instagram.com/cuadros_y.mas_cuadros?igshid=YmMyMTA2M2Y="  target="_blank">
                <img src="../static/img/iconoi.png" alt="Instagram">
                &nbsp &nbsp&nbsp &nbsp
            </a>

            <a class="botonContacto" href="https://www.tiktok.com/@cuadros_y.mas_cuadros"  target="_blank">
                <img src="../static/img/iconot.png" alt="TikTok">
            </a>
            <br><br>
          
            <h5 class="textos" id="txt4">+57 3175275953
            
                <img src="../static/img/icontel.png" width="30" height="30" alt="Tel">
                
            </h5>

            <br>
            <h5 class="textos" id="txt4">cuadrosymascuadroscyc@hotmail.com
            
                <img src="../static/img/iconcor.png" width="30" height="30" alt="Tel">
                
            </h5>
        </div>
    </div>
  


{% endblock %}

templates/error.html
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cuadros y más cuadros</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">
    <link rel="icon" type="image/x-icon" href="../static/img/icon_pag.png">
    <link rel="stylesheet" type="text/css" href="../static/css/style.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../static/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="../static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <link rel="stylesheet" href="../static/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <link rel="stylesheet" href="../static/plugins/jqvmap/jqvmap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/adminlte.min.css')}}">
    <link rel="stylesheet" href="../static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <link rel="stylesheet" href="../static/plugins/daterangepicker/daterangepicker.css">
    <link rel="stylesheet" href="../static/plugins/summernote/summernote-bs4.min.css">
    <link rel="stylesheet" href="../static/css/adminlte.min.css">
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Fuzzy+Bubbles:wght@700&family=Source+Serif+Pro:ital,wght@1,600&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script type="text/javascript" src="../static/js/bootstrap.min.js"></script>

    <script >
		var btnwpp = new Audio();
		btnwpp.src="../static/audios/Whatsapp.mp3"
	</script>
</head>

    <body style="background-color:black;">

        <div class="conten">
            <div class="conten__img">
                <img src="../static/img/404.png" alt="">
                <p class="conten__number">
                    404
                </p>
            </div>
            <div class="conten__Description">
                <p class="conten__error">
                    UPSSSS!!!! Algo salio mal, pagina no encontrada.
                </p>
                <a href="/" class="conten__button">SACAME DE AQUI!.</a>
            </div>
        </div>

        <script src="../static/plugins/jquery/jquery.min.js"></script>
    <script src="../static/plugins/jquery-ui/jquery-ui.min.js"></script>
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <script src="../static/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="../static/plugins/chart.js/Chart.min.js"></script>
    <script src="../static/plugins/sparklines/sparkline.js"></script>
    <script src="../static/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="../static/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <script src="../static/plugins/jquery-knob/jquery.knob.min.js"></script>
    <script src="../static/plugins/moment/moment.min.js"></script>
    <script src="../static/plugins/daterangepicker/daterangepicker.js"></script>
    <script src="../static/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <script src="../static/plugins/summernote/summernote-bs4.min.js"></script>
    <script src="../static/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <script src="../static/js/adminlte.js"></script>
    <script src="../static/js/pages/dashboard.js"></script>
    <script src="../static/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
    <script src="../static/js/adminlte.min.js"></script>   
    <script src="../static/js/confirmacion.js"></script>

    </body>

templates/error1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cuadros y más cuadros</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">
    <link rel="icon" type="image/x-icon" href="../static/img/icon_pag.png">
    <link rel="stylesheet" type="text/css" href="../static/css/style.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../static/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="../static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <link rel="stylesheet" href="../static/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <link rel="stylesheet" href="../static/plugins/jqvmap/jqvmap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/adminlte.min.css')}}">
    <link rel="stylesheet" href="../static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <link rel="stylesheet" href="../static/plugins/daterangepicker/daterangepicker.css">
    <link rel="stylesheet" href="../static/plugins/summernote/summernote-bs4.min.css">
    <link rel="stylesheet" href="../static/css/adminlte.min.css">
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Fuzzy+Bubbles:wght@700&family=Source+Serif+Pro:ital,wght@1,600&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script type="text/javascript" src="../static/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{{url_for("static", filename='/css/error404.css')}}">
    <title>{{error.code }}</title>
</head>

<body style="background-color:black;">
    <div class="conten">
        <h1 style="color:white">Solicitud incorrecta <br> 
            Error
            <br>
        </h1>
    
        <div class="conten__img">
            <p class="conten__number">

                <img src="../static/img/404.png" alt="">
                
            </p>
        </div>   
                
        <br>
        <div class="conten__Description">
            <p class="conten__error">
                <section class="error-container" >
                    <span>{{ error.code }}</span>
                </section>
            </p> 
        </div>
        <h5 style="color:white">UPSSSS!!!! Algo salio mal, pagina no encontrada.</h5> <br>
         <a href="/" class="conten__button">SACAME DE AQUI!.</a>
    </div>
</body>
</html>

templates/index.html
{% extends './layout.html' %}

templates/layout.html
<!DOCTYPE html> 
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cuadros y más cuadros</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">
    <link rel="icon" type="image/x-icon" href="../static/img/icon_pag.png">
    <link rel="stylesheet" type="text/css" href="../static/css/style.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../static/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="../static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <link rel="stylesheet" href="../static/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <link rel="stylesheet" href="../static/plugins/jqvmap/jqvmap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/adminlte.min.css')}}">
    <link rel="stylesheet" href="../static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <link rel="stylesheet" href="../static/plugins/daterangepicker/daterangepicker.css">
    <link rel="stylesheet" href="../static/plugins/summernote/summernote-bs4.min.css">
    <link rel="stylesheet" href="../static/css/adminlte.min.css">
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v2.1.9/css/unicons.css">
    <link rel="stylesheet" href="../static/css/styleLog.css">
    <link href="https://fonts.googleapis.com/css2?family=Fuzzy+Bubbles:wght@700&family=Source+Serif+Pro:ital,wght@1,600&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script type="text/javascript" src="../static/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 
    <script >
		var btnwpp = new Audio();
		btnwpp.src="../static/audios/Whatsapp.mp3"
	</script>
</head>
{% block contenidolog %} {% endblock %}
<body class="hold-transition sidebar-mini layout-fixed">
   
    <div class="wrapper">

        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src="../static/img/logonegro.png" alt="C&C" height="150" width="150">
        </div>

        <nav class="main-header navbar navbar-expand navbar-blue navbar-dark">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" role="button" href="{{ url_for('logout')}}">
                        <i class="fas fa-user-slash" ></i>
                        
                    </a>
                </li> 
                <li class="nav-item">
                    <a class="nav-link" role="button" href="{{ url_for('carritocompras.carrito')}}">
                        <i class="fas fa-shopping-cart"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" role="button" href="{{ url_for('paginacion.precios')}}">
                        <i class="fas fa-scroll"></i>
                    </a>
                </li>   
            </ul>
        </nav>

        <!--  -->

        <aside class="main-sidebar sidebar-dark-info elevation-4">
            <a href="/sesion" class="brand-link">
                <img src="../static/img/CycLogo.png" alt="C&C logo" class="brand-image img-circle elevation-3">
                <span class="brand-text font-weight-light">C&C</span>
            </a>

            <div class="sidebar">

                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item menu-close">
                            <a href="" class="nav-link active">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Opciones
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="{{ url_for('tipo.tipos')}}" class="nav-link">
                                        <i class="nav-icon fas fa-star"></i>
                                        <p>Cuadros</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="{{ url_for('contacto.contactos')}}" class="nav-link">
                                <i class="nav-icon fas fa-users"></i>
                                <p>Contactanos</p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{{ url_for('queja.quejas')}}" class="nav-link">
                                <i class="nav-icon fas fa-file"></i>
                                <p>Quejas y reclamos</p>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>

        <!--*******************************************inicio contenido ventanas****************************************************--> 
         {% block contenido2 %} {% endblock %} 
        <!--*******************************************fin contenido ventanas****************************************************--> 

            <footer>
                <a class="appWhatsapp" href="https://wa.me/message/BH3BJKU6EVRON1"  onmousedown="btnwpp.play()" target="_blank">
                    <img src="../static/img/logowpp.png" alt="WhatsApp"> 
                </a>
                <div id="fb-root"></div>
            </footer>         

            </section>
            
            </div>

            <footer class="main-footer">
                <strong>Copyright &copy; 2023 <a href="https://www.facebook.com/Cuadrosymascuadros999"  target="_blank">@Cuadrosymascuadros999</a>.</strong> Todos los derechos reservados.
                <div class="float-right d-none d-sm-inline-block">
                    <b>Version</b> 1.0.0
                </div>
            </footer>

            <aside class="control-sidebar control-sidebar-dark">
            </aside>

        </div>
      
    <script src="../static/plugins/jquery/jquery.min.js"></script>
    <script src="../static/plugins/jquery-ui/jquery-ui.min.js"></script>
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <script src="../static/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="../static/plugins/chart.js/Chart.min.js"></script>
    <script src="../static/plugins/sparklines/sparkline.js"></script>
    <script src="../static/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="../static/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <script src="../static/plugins/jquery-knob/jquery.knob.min.js"></script>
    <script src="../static/plugins/moment/moment.min.js"></script>
    <script src="../static/plugins/daterangepicker/daterangepicker.js"></script>
    <script src="../static/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <script src="../static/plugins/summernote/summernote-bs4.min.js"></script>
    <script src="../static/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <script src="../static/js/adminlte.js"></script>
    <script src="../static/js/pages/dashboard.js"></script>
    <script src="../static/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
    <script src="../static/js/adminlte.min.js"></script>   
    <script src="../static/js/confirmacion.js"></script>
</body>



</html>

templates/menu.html
{% extends './layout.html' %}

{% block contenido2 %} 
<div class="content-wrapper" style="background-image: url('../static/img/fondo4.png');">

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="titulom">Inicio</h1>
                </div>
            </div>
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-4 col-6">
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>Cuadros</h3>
                            <p> Tipos de cuadros</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-bag"></i>
                        </div>
                        <a href="{{ url_for('tipo.tipos')}}" class="small-box-footer">Click para continuar  <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <div class="col-lg-4 col-6">
                    <div class="small-box bg-warning">
                        <div class="inner">
                            <h3>Contactos</h3>
                            <p>Comunicate con nosotros</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-add"></i>
                        </div>
                        <a href="{{ url_for('contacto.contactos')}}" class="small-box-footer">Click para continuar <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <div class="col-lg-4 col-6">
                    <div class="small-box bg-danger">
                        <div class="inner">
                            <h3>P.Q.R.S.</h3>
                            <p>Detalla tu peticion</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-cloud"></i>
                        </div>
                        <a href="{{ url_for('queja.quejas')}}" class="small-box-footer">Click para continuar <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
            </div>

        <br>
        <div id="contenedor" class="col-12" align="center">
            <img src="../static/img/logoCuadros.png" alt="C&C" width="300" height="300">
        </div>


{% endblock %}

templates/precio.html
{% extends './layout.html' %}


{% block contenido2 %} 


    <div class="content-wrapper" style="background-image: url('../static/img/fondo4.png');">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">

                    <br><br>
                    <div id="contenedor" class="col-12" align="center">
                        <div id="contenedor2" class="col-9" align="left">
                            <div class="card border-info">
                                <div class="card-body">
                                    <ul class="list-group list-group-light">
                                        <li class="list-group-item">
                                            <div class="container">
                                                <div class="row">
                                                    <div class="col-12">
                                                        <section class="content">
                                                            <div class="row">
                                                                <div class="col-md-12">
                                                                    <form class="was-validated">
                                                                        <div class="card2 card-primary">

                                                                            <div class="card-header">
                                                                                <h3 class="card-title">Consulta el precio</h3>
                                                                            </div>
                                                                            <div class="container " style="background-color: #BFC4C4;" align="center">
                                                                                <img src="../static/img/proxim.png" alt="Facebook">


                                                                            </div>
                                                                        </div>
                                                                    </form>
                                                                </div>
                                                            </div>
                                                    </div>
                                                    </section>
                                                </div>
                                            </div>
                                </div>
                                </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>
    </div>
{% endblock %}